spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1001101lb
    url: jdbc:mysql://localhost:3306/chat_server_netty?serverTimezone=Asia/Shanghai

server:
  port: 7777

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
